/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * Config plugin · an explicit cleartext policy per build variant (F-01 · F-05)
 *
 * Every transport default in `app.json` is `http://` / `ws://`, because the
 * documented developer path is a LAN backend with no TLS in front of it
 * (ops/README.md). Android 9+ blocks cleartext in release builds by default and
 * Expo's template re-enables it for DEBUG builds only, through
 * `android/app/src/debug/AndroidManifest.xml` (`usesCleartextTraffic="true"`,
 * `tools:replace`). That is the right split — but it was implicit, generated,
 * and nowhere in this repository.
 *
 * ★ WHY IT MUST NOT BE "true" IN RELEASE ★
 * The SOS envelope is SIGNED, not encrypted: `Canonical` emits `"duress":true`
 * in the clear. F-01's padding exists to defeat an observer on the network;
 * shipping cleartext would hand that observer the duress bit, the member and
 * device ids and every WebSocket frame. A release build that cannot reach an
 * `http://` host is therefore correct, and it now says so in the build log
 * (`withKavachReleaseGuard`) and in the app (`CONFIG.serverConfigured`) instead
 * of degrading to "SMS only" in silence.
 *
 * ★ WHAT THIS WRITES ★
 * One `network_security_config` resource, two source sets:
 *   app/src/main/res/xml/kavach_network_security.xml   cleartext FORBIDDEN
 *   app/src/debug/res/xml/kavach_network_security.xml  cleartext permitted
 * The debug source set outranks main for debug variants, so the dev client and
 * `expo run:android` keep the LAN path and every release variant (`preview`,
 * `production`) refuses it. A network security config takes precedence over
 * `android:usesCleartextTraffic`, so the template's debug attribute becomes
 * redundant rather than contradictory.
 *
 * This file is also where F-05's "own TLS chain, own pin" for `apiDirect`
 * belongs (a `<domain-config>` with a `<pin-set>`). No pin is written: there is
 * no origin to pin yet, and an invented pin would brick every request.
 *
 * `renderXml` / `filesFor` / `setNetworkSecurityConfig` are exported and pure
 * so `test/network-security.test.ts` can check them without a build.
 * ═══════════════════════════════════════════════════════════════════════════════
 */
const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');

const RESOURCE_NAME = 'kavach_network_security';

/**
 * Only `cleartextTrafficPermitted` is stated. `<trust-anchors>` is deliberately
 * omitted so the platform default (system CAs, no user CAs) is inherited
 * unchanged — this plugin decides cleartext, not trust.
 */
function renderXml(cleartextPermitted) {
  const why = cleartextPermitted
    ? 'DEBUG variant: the LAN developer path (ops/README.md) has no TLS. Never shipped.'
    : 'RELEASE variant: the signed SOS envelope carries the duress bit in the clear (F-01).';
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by plugins/withKavachNetworkSecurity.js on every prebuild. Do not hand-edit. -->',
    `<!-- ${why} -->`,
    '<network-security-config>',
    `    <base-config cleartextTrafficPermitted="${cleartextPermitted ? 'true' : 'false'}" />`,
    '</network-security-config>',
    '',
  ].join('\n');
}

/** The two files, relative to the Android project root. Pure. */
function filesFor(platformProjectRoot) {
  return [
    {
      path: path.join(platformProjectRoot, 'app', 'src', 'main', 'res', 'xml', `${RESOURCE_NAME}.xml`),
      contents: renderXml(false),
    },
    {
      path: path.join(platformProjectRoot, 'app', 'src', 'debug', 'res', 'xml', `${RESOURCE_NAME}.xml`),
      contents: renderXml(true),
    },
  ];
}

/** Point `<application>` at the resource. Pure over the parsed manifest. */
function setNetworkSecurityConfig(androidManifest) {
  const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.$['android:networkSecurityConfig'] = `@xml/${RESOURCE_NAME}`;
  return androidManifest;
}

module.exports = function withKavachNetworkSecurity(config) {
  config = withAndroidManifest(config, (cfg) => {
    cfg.modResults = setNetworkSecurityConfig(cfg.modResults);
    return cfg;
  });
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      for (const file of filesFor(cfg.modRequest.platformProjectRoot)) {
        fs.mkdirSync(path.dirname(file.path), { recursive: true });
        fs.writeFileSync(file.path, file.contents);
      }
      return cfg;
    },
  ]);
  return config;
};

module.exports.RESOURCE_NAME = RESOURCE_NAME;
module.exports.renderXml = renderXml;
module.exports.filesFor = filesFor;
module.exports.setNetworkSecurityConfig = setNetworkSecurityConfig;
