/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * Config plugin · keep React Native OUT of the :t0 process
 *
 * KavachForegroundService, BootReceiver and ShutdownReceiver all declare
 * android:process=":t0" so the Tier-0 agent survives an OOM kill of the JS heap
 * (see modules/kavach-t0/.../AndroidManifest.xml).
 *
 * ★ THE PROBLEM THIS SOLVES ★
 * Android instantiates the Application class in EVERY process of the app, not
 * just the main one. Expo's generated MainApplication.onCreate() calls
 * SoLoader.init(), builds the ReactHost and — with the New Architecture — loads
 * the native RN libraries. Left alone, all of that runs inside :t0 as well.
 *
 * The agent is then no longer the ~15 MB process the low-memory killer ignores;
 * it carries the entire React Native runtime it was split out to escape. The
 * isolation is nominal, memory is doubled for no benefit, and boot is slower at
 * exactly the moment (LOCKED_BOOT_COMPLETED, before first unlock) when the agent
 * is racing to come up. On some OEM builds SoLoader in a Direct-Boot process
 * throws outright, because credential-protected storage is not yet available.
 *
 * ★ WHY A PLUGIN AND NOT A COMMENT ★
 * MainApplication.kt is REGENERATED by `expo prebuild` on every EAS build, so a
 * hand edit lasts exactly until the next build and then vanishes silently. The
 * only durable place for this is a plugin that re-applies it each time.
 *
 * The guard is a no-op in the main process, so nothing about normal startup
 * changes.
 * ═══════════════════════════════════════════════════════════════════════════════
 */
const { withMainApplication } = require('expo/config-plugins');

const GUARD_MARKER = 'kavachIsT0Process';

/** Kotlin inserted at the top of onCreate(), before any RN initialisation. */
const KOTLIN_GUARD = `    // ★ Kavach T0 — injected by plugins/withKavachT0Process.js. Do not hand-edit;
    // MainApplication.kt is regenerated by prebuild on every build.
    // The Tier-0 agent runs in ":t0" (see the kavach-t0 manifest). Android creates
    // the Application in that process too, and booting SoLoader + ReactHost there
    // would put the whole React Native runtime inside the process we split out
    // precisely to keep small enough to survive an OOM kill.
    if (${GUARD_MARKER}()) {
      super.onCreate()
      return
    }
`;

const KOTLIN_HELPER = `
  /** True when this Application instance is being created in the ":t0" process. */
  private fun ${GUARD_MARKER}(): Boolean {
    val pid = android.os.Process.myPid()
    val am = getSystemService(android.content.Context.ACTIVITY_SERVICE) as? android.app.ActivityManager
    val name = am?.runningAppProcesses?.firstOrNull { it.pid == pid }?.processName
      ?: return false
    return name.endsWith(":t0")
  }
`;

/** Java variant, for the (rare) template that still emits MainApplication.java. */
const JAVA_GUARD = `    // ★ Kavach T0 — injected by plugins/withKavachT0Process.js. See the Kotlin
    // variant for the rationale. Keeps React Native out of the ":t0" process.
    if (${GUARD_MARKER}()) {
      super.onCreate();
      return;
    }
`;

const JAVA_HELPER = `
  private boolean ${GUARD_MARKER}() {
    int pid = android.os.Process.myPid();
    android.app.ActivityManager am =
        (android.app.ActivityManager) getSystemService(android.content.Context.ACTIVITY_SERVICE);
    if (am == null || am.getRunningAppProcesses() == null) return false;
    for (android.app.ActivityManager.RunningAppProcessInfo p : am.getRunningAppProcesses()) {
      if (p.pid == pid && p.processName != null) return p.processName.endsWith(":t0");
    }
    return false;
  }
`;

/**
 * Insert `guard` immediately after the opening brace of onCreate(), and `helper`
 * before the final closing brace of the class.
 */
function inject(contents, guard, helper, isKotlin) {
  if (contents.includes(GUARD_MARKER)) return contents; // already applied
  const signature = isKotlin
    ? /override\s+fun\s+onCreate\s*\(\s*\)\s*\{/
    : /public\s+void\s+onCreate\s*\(\s*\)\s*\{/;

  const match = contents.match(signature);
  if (!match || match.index === undefined) {
    // Fail loudly. A silently un-applied guard means the isolation the whole T0
    // design depends on is gone, and nothing else in the build would report it.
    throw new Error(
      '[withKavachT0Process] could not find onCreate() in MainApplication — ' +
        'the Expo template changed shape. The :t0 process would boot React Native. ' +
        'Fix this plugin rather than removing it.',
    );
  }

  const at = match.index + match[0].length;
  let out = contents.slice(0, at) + '\n' + guard + contents.slice(at);

  const lastBrace = out.lastIndexOf('}');
  if (lastBrace === -1) throw new Error('[withKavachT0Process] malformed MainApplication');
  out = out.slice(0, lastBrace) + helper + out.slice(lastBrace);
  return out;
}

/**
 * Apply the guard to one MainApplication source. Pure: text in, text out.
 * Exported so it can be tested directly — monkey-patching `withMainApplication`
 * from a test cannot work, because this module destructures it at load time.
 */
function applyGuard(contents, language) {
  const isKotlin = language === 'kt';
  return inject(
    contents,
    isKotlin ? KOTLIN_GUARD : JAVA_GUARD,
    isKotlin ? KOTLIN_HELPER : JAVA_HELPER,
    isKotlin,
  );
}

module.exports = function withKavachT0Process(config) {
  return withMainApplication(config, (cfg) => {
    cfg.modResults.contents = applyGuard(cfg.modResults.contents, cfg.modResults.language);
    return cfg;
  });
};

module.exports.applyGuard = applyGuard;
module.exports.GUARD_MARKER = GUARD_MARKER;
