// Code generated by tools/smgen.mjs from spec/state-machine.yaml. DO NOT EDIT.
// Regenerate with:  npm run gen

/* eslint-disable */

export const SPEC_VERSION = 3;

export const INCIDENT_STATES = [
  'IDLE',
  'WATCH',
  'SUSPECT',
  'PROBE',
  'PENDING',
  'FALSE_ALARM',
  'ACTIVE_L1',
  'ACTIVE_L1_SILENT',
  'ACTIVE_L2',
  'ACTIVE_L3',
  'OWNED',
  'RESOLVING',
  'RESOLVED',
  'DORMANT',
] as const;
export type IncidentState = (typeof INCIDENT_STATES)[number];

export const INCIDENT_EVENTS = [
  'CONTEXT_ELEVATED',
  'CONTEXT_ENDED',
  'SENSOR_ANOMALY',
  'CONFIDENCE',
  'USER_FINE',
  'MANUAL_TRIGGER',
  'PIN_CORRECT',
  'PIN_DURESS',
  'CANCEL_WINDOW_EXPIRED',
  'PROBE_TIMEOUT',
  'NO_ACK',
  'CLAIM',
  'RELEASE',
  'PROGRESS_WATCHDOG',
  'ON_SCENE',
  'TWO_PARTY_CONFIRM',
  'SELF_CLEAR_PIN',
  'AUTO_QUIESCE',
  'REESCALATE',
  'MOTION_RESUMED',
] as const;
export type IncidentEvent = (typeof INCIDENT_EVENTS)[number];

export const TERMINAL_STATES: ReadonlySet<IncidentState> = new Set([
  'FALSE_ALARM',
  'RESOLVED',
  'DORMANT',
]);

/** States in which the incident is live: arms escalation timers, blocks deploys. */
export const ACTIVE_STATES: ReadonlySet<IncidentState> = new Set([
  'PENDING',
  'ACTIVE_L1',
  'ACTIVE_L1_SILENT',
  'ACTIVE_L2',
  'ACTIVE_L3',
  'OWNED',
  'RESOLVING',
]);

export interface Transition {
  readonly from: IncidentState;
  readonly to: IncidentState;
  readonly on: IncidentEvent;
  readonly guard?: string;
  readonly afterS?: number;
}

export const TRANSITIONS: readonly Transition[] = [
  { from: 'IDLE', to: 'WATCH', on: 'CONTEXT_ELEVATED' },
  { from: 'WATCH', to: 'IDLE', on: 'CONTEXT_ENDED' },
  { from: 'IDLE', to: 'SUSPECT', on: 'SENSOR_ANOMALY' },
  { from: 'WATCH', to: 'SUSPECT', on: 'SENSOR_ANOMALY', guard: 'lowerThreshold' },
  { from: 'SUSPECT', to: 'IDLE', on: 'MOTION_RESUMED' },
  { from: 'SUSPECT', to: 'PROBE', on: 'CONFIDENCE', guard: 'confidenceMedium' },
  { from: 'SUSPECT', to: 'PENDING', on: 'CONFIDENCE', guard: 'confidenceHigh' },
  { from: 'PROBE', to: 'IDLE', on: 'USER_FINE' },
  { from: 'PROBE', to: 'PENDING', on: 'PROBE_TIMEOUT', afterS: 45 },
  { from: 'IDLE', to: 'PENDING', on: 'MANUAL_TRIGGER' },
  { from: 'WATCH', to: 'PENDING', on: 'MANUAL_TRIGGER' },
  { from: 'PENDING', to: 'FALSE_ALARM', on: 'PIN_CORRECT' },
  { from: 'PENDING', to: 'ACTIVE_L1_SILENT', on: 'PIN_DURESS' },
  { from: 'PENDING', to: 'ACTIVE_L1', on: 'CANCEL_WINDOW_EXPIRED' },
  { from: 'ACTIVE_L1', to: 'ACTIVE_L2', on: 'NO_ACK', afterS: 90 },
  { from: 'ACTIVE_L1_SILENT', to: 'ACTIVE_L2', on: 'NO_ACK', afterS: 90 },
  { from: 'ACTIVE_L2', to: 'ACTIVE_L3', on: 'NO_ACK', afterS: 180 },
  { from: 'ACTIVE_L1', to: 'OWNED', on: 'CLAIM' },
  { from: 'ACTIVE_L1_SILENT', to: 'OWNED', on: 'CLAIM' },
  { from: 'ACTIVE_L2', to: 'OWNED', on: 'CLAIM' },
  { from: 'ACTIVE_L3', to: 'OWNED', on: 'CLAIM' },
  { from: 'OWNED', to: 'ACTIVE_L2', on: 'RELEASE' },
  { from: 'OWNED', to: 'ACTIVE_L2', on: 'PROGRESS_WATCHDOG', afterS: 300 },
  { from: 'OWNED', to: 'RESOLVING', on: 'ON_SCENE' },
  { from: 'RESOLVING', to: 'RESOLVED', on: 'TWO_PARTY_CONFIRM' },
  { from: 'ACTIVE_L1', to: 'RESOLVED', on: 'SELF_CLEAR_PIN' },
  { from: 'ACTIVE_L2', to: 'RESOLVED', on: 'SELF_CLEAR_PIN' },
  { from: 'ACTIVE_L3', to: 'RESOLVED', on: 'SELF_CLEAR_PIN' },
  { from: 'ACTIVE_L1', to: 'DORMANT', on: 'AUTO_QUIESCE', afterS: 21600 },
  { from: 'ACTIVE_L1_SILENT', to: 'DORMANT', on: 'AUTO_QUIESCE', afterS: 21600 },
  { from: 'ACTIVE_L2', to: 'DORMANT', on: 'AUTO_QUIESCE', afterS: 21600 },
  { from: 'ACTIVE_L3', to: 'DORMANT', on: 'AUTO_QUIESCE', afterS: 21600 },
  { from: 'OWNED', to: 'DORMANT', on: 'AUTO_QUIESCE', afterS: 21600 },
  { from: 'ACTIVE_L1', to: 'ACTIVE_L2', on: 'REESCALATE' },
  { from: 'ACTIVE_L2', to: 'ACTIVE_L3', on: 'REESCALATE' },
];

/** Guards the runtime must supply. A missing guard evaluates to TRUE (fail open, ADR-018). */
export type GuardSet = Partial<Record<string, boolean>>;

/**
 * Pure transition function. No side effects, no I/O, no clock.
 * Returns null when the event does not apply in the current state —
 * unknown events are ALWAYS ignored, never thrown (a crash in T0 is fatal).
 */
export function nextState(
  from: IncidentState,
  event: IncidentEvent,
  guards: GuardSet = {},
): IncidentState | null {
  for (const t of TRANSITIONS) {
    if (t.from !== from || t.on !== event) continue;
    if (t.guard !== undefined && guards[t.guard] !== true) continue;
    return t.to;
  }
  return null;
}

/** The scheduled timeout (seconds) for a state, if the spec defines one. */
export function timeoutsFor(state: IncidentState): Transition[] {
  return TRANSITIONS.filter((t) => t.from === state && t.afterS !== undefined);
}

export function isTerminal(s: IncidentState): boolean { return TERMINAL_STATES.has(s); }
export function isActive(s: IncidentState): boolean { return ACTIVE_STATES.has(s); }

/** Fold an event log into a state. The projection is always recomputable (PRD §7.5). */
export function fold(
  events: ReadonlyArray<{ event: IncidentEvent; guards?: GuardSet }>,
  from: IncidentState = 'IDLE',
): IncidentState {
  let s = from;
  for (const e of events) {
    const n = nextState(s, e.event, e.guards ?? {});
    if (n !== null) s = n;
  }
  return s;
}
