/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * CONFIG PLUGIN · :t0 PROCESS GUARD
 *
 * plugins/withKavachT0Process.js rewrites MainApplication so React Native never
 * boots inside the ":t0" process. MainApplication.kt is regenerated by prebuild
 * on every EAS build, so this plugin is the ONLY thing standing between the
 * Tier-0 agent and the full RN runtime being loaded into it.
 *
 * If the Expo template changes shape, the plugin's regex stops matching. It
 * throws rather than silently skipping — but a throw during a cloud build is a
 * 15-minute round trip to discover. These tests catch it locally in a second.
 * ═══════════════════════════════════════════════════════════════════════════════
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require_ = createRequire(import.meta.url);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** The shape Expo SDK 57 emits for a New Architecture Kotlin app. */
const KOTLIN_TEMPLATE = [
  'package in.example.kavach',
  '',
  'import android.app.Application',
  'import com.facebook.soloader.SoLoader',
  '',
  'class MainApplication : Application(), ReactApplication {',
  '  override val reactNativeHost: ReactNativeHost = ReactNativeHostWrapper(this, object : DefaultReactNativeHost(this) {})',
  '',
  '  override fun onCreate() {',
  '    super.onCreate()',
  '    SoLoader.init(this, OpenSourceMergedSoMapping)',
  '    loadReactNative(this)',
  '    ApplicationLifecycleDispatcher.onApplicationCreate(this)',
  '  }',
  '}',
  '',
].join('\n');

const JAVA_TEMPLATE = [
  'package in.example.kavach;',
  '',
  'public class MainApplication extends Application implements ReactApplication {',
  '  @Override',
  '  public void onCreate() {',
  '    super.onCreate();',
  '    SoLoader.init(this, false);',
  '  }',
  '}',
  '',
].join('\n');

/**
 * The plugin exports its injector as a pure function precisely so this test can
 * call it. Intercepting `withMainApplication` does not work: the plugin
 * destructures that import at module load, so a later patch of the module object
 * is never seen.
 */
const { applyGuard } = require_(resolve(ROOT, 'plugins/withKavachT0Process.js')) as {
  applyGuard: (contents: string, language: 'kt' | 'java') => string;
};

const applyPlugin = (contents: string, language: 'kt' | 'java') => applyGuard(contents, language);

test('the guard is injected into a Kotlin MainApplication', () => {
  const out = applyPlugin(KOTLIN_TEMPLATE, 'kt');
  assert.match(out, /kavachIsT0Process\(\)/, 'guard call missing');
  assert.match(out, /private fun kavachIsT0Process/, 'helper missing');
});

test('★ the guard runs BEFORE SoLoader and the React host', () => {
  // The entire point: returning after SoLoader.init would have already paid the
  // memory and Direct-Boot cost the guard exists to avoid.
  const out = applyPlugin(KOTLIN_TEMPLATE, 'kt');
  const guardAt = out.indexOf('kavachIsT0Process()');
  const soLoaderAt = out.indexOf('SoLoader.init');
  const rnAt = out.indexOf('loadReactNative');
  assert.ok(guardAt > -1 && soLoaderAt > -1, 'expected both markers present');
  assert.ok(guardAt < soLoaderAt, 'guard must precede SoLoader.init');
  assert.ok(guardAt < rnAt, 'guard must precede loadReactNative');
});

test('the guard still calls super.onCreate() before returning', () => {
  // Skipping Application.onCreate() entirely breaks ContentProviders and the
  // system's own bookkeeping in that process.
  const out = applyPlugin(KOTLIN_TEMPLATE, 'kt');
  const guarded = out.slice(out.indexOf('kavachIsT0Process()'));
  const block = guarded.slice(0, guarded.indexOf('}') + 1);
  assert.match(block, /super\.onCreate\(\)/, 'super.onCreate() missing from the early-return');
});

test('applying the plugin twice is a no-op', () => {
  const once = applyPlugin(KOTLIN_TEMPLATE, 'kt');
  const twice = applyPlugin(once, 'kt');
  assert.equal(twice, once, 'plugin is not idempotent — prebuild would stack guards');
});

test('the Java template is handled too', () => {
  const out = applyPlugin(JAVA_TEMPLATE, 'java');
  assert.match(out, /kavachIsT0Process\(\)/);
  assert.match(out, /private boolean kavachIsT0Process/);
  assert.ok(out.indexOf('kavachIsT0Process()') < out.indexOf('SoLoader.init'));
});

test('★ the plugin FAILS LOUDLY if the template no longer has onCreate()', () => {
  // Silently skipping would ship an APK whose T0 process carries the whole RN
  // runtime — the isolation would be nominal and nothing would report it.
  assert.throws(
    () => applyPlugin('class MainApplication : Application() { }', 'kt'),
    /could not find onCreate/,
    'plugin must throw rather than skip',
  );
});

test('the plugin is registered in app.json', () => {
  const appJson = require_(resolve(ROOT, 'app.json')) as {
    expo: { plugins: (string | unknown[])[] };
  };
  const registered = appJson.expo.plugins.some(
    (p) => (typeof p === 'string' ? p : String((p as unknown[])[0])).includes('withKavachT0Process'),
  );
  assert.ok(registered, 'withKavachT0Process is not in app.json plugins — it would never run');
});
