package envelope

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// ═══════════════════════════════════════════════════════════════════════════════
// CROSS-LANGUAGE CONFORMANCE
//
// The TypeScript client builds and signs the emergency envelope. This package
// verifies it. Both implement canonicalisation independently, and until this
// file existed nothing proved they produce identical bytes.
//
// ★ WHY THIS IS THE HIGHEST-VALUE TEST IN THE BACKEND ★
// A one-character divergence breaks the Ed25519 signature on EVERY real
// incident. And because ingest fails OPEN by design (ADR-018), it would not
// error, would not page, and would not show up in any dashboard — it would
// silently flag 100% of genuine emergencies UNVERIFIED and carry on. Invisible
// in testing, invisible in production, and it defeats the entire signature layer
// precisely when it matters.
//
// Vectors are generated by mobile/test/emit-crosslang-vectors.ts. A diff in
// testdata/vectors.json means client and server have diverged — regenerate ONLY
// when the canonical form changed on purpose.
// ═══════════════════════════════════════════════════════════════════════════════

type vectors struct {
	FixedEnvelopeSize int    `json:"fixedEnvelopeSize"`
	GroupSecretB64    string `json:"groupSecretB64"`
	Envelopes         []struct {
		Name       string `json:"name"`
		Body       string `json:"body"`
		Signature  string `json:"signature"`
		PublicKey  string `json:"publicKey"`
		Duress     bool   `json:"duress"`
		ByteLength int    `json:"byteLength"`
	} `json:"envelopes"`
	SMS []struct {
		Name         string  `json:"name"`
		Text         string  `json:"text"`
		Length       int     `json:"length"`
		IncidentID   string  `json:"incidentId"`
		Inc8         string  `json:"inc8"`
		ExpectedCode string  `json:"expectedCode"`
		Lat          float64 `json:"lat"`
		Lon          float64 `json:"lon"`
	} `json:"sms"`
	Inc8 []struct {
		IncidentID string `json:"incidentId"`
		Inc8       string `json:"inc8"`
	} `json:"inc8"`
	SMSTag struct {
		GroupSecretB64 string `json:"groupSecretB64"`
		Payload        string `json:"payload"`
		Tag            string `json:"tag"`
	} `json:"smsTag"`
}

func loadVectors(t *testing.T) vectors {
	t.Helper()
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v (regenerate with mobile/test/emit-crosslang-vectors.ts)", err)
	}
	var v vectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(v.Envelopes) == 0 || len(v.SMS) == 0 {
		t.Fatal("vectors file is empty")
	}
	return v
}

// TestClientEnvelopeVerifies is the one that matters: bytes the CLIENT produced,
// verified by the SERVER's Ed25519 path.
func TestClientEnvelopeVerifies(t *testing.T) {
	v := loadVectors(t)
	for _, e := range v.Envelopes {
		t.Run(e.Name, func(t *testing.T) {
			pub, err := base64.StdEncoding.DecodeString(e.PublicKey)
			if err != nil {
				t.Fatalf("decode pubkey: %v", err)
			}
			if !VerifyB64([]byte(e.Body), e.Signature, ed25519.PublicKey(pub)) {
				t.Fatal("signature from the TypeScript client did NOT verify — " +
					"client and server canonicalisation have diverged")
			}
		})
	}
}

// TestClientEnvelopeParses proves the server understands every field the client
// emits, with no anomalies flagged on a well-formed envelope.
func TestClientEnvelopeParses(t *testing.T) {
	v := loadVectors(t)
	for _, e := range v.Envelopes {
		t.Run(e.Name, func(t *testing.T) {
			env, anomaly, err := Parse([]byte(e.Body))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if anomaly != 0 {
				t.Fatalf("well-formed client envelope flagged anomalies: %s", anomaly)
			}
			if env.Duress != e.Duress {
				t.Fatalf("duress round-trip: got %v want %v", env.Duress, e.Duress)
			}
		})
	}
}

// TestCanonicalRoundTripMatchesClient re-canonicalises the parsed envelope and
// requires the SAME bytes back. This is the actual divergence detector: Parse
// then Canonical must be the identity function over client output.
func TestCanonicalRoundTripMatchesClient(t *testing.T) {
	v := loadVectors(t)
	for _, e := range v.Envelopes {
		t.Run(e.Name, func(t *testing.T) {
			env, _, err := Parse([]byte(e.Body))
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			got := string(Canonical(env))
			if got != e.Body {
				// Report the first differing offset — a whole 1024-byte diff is unreadable.
				n := len(got)
				if len(e.Body) < n {
					n = len(e.Body)
				}
				at := n
				for i := 0; i < n; i++ {
					if got[i] != e.Body[i] {
						at = i
						break
					}
				}
				lo := at - 40
				if lo < 0 {
					lo = 0
				}
				t.Fatalf("canonical form diverged at byte %d\n  server: %.80q\n  client: %.80q",
					at, got[lo:], e.Body[lo:])
			}
		})
	}
}

// ★ F-01 / threat T4. The property the whole duress design rests on.
func TestDuressIsNotDistinguishableBySize(t *testing.T) {
	v := loadVectors(t)
	for _, e := range v.Envelopes {
		if len(e.Body) != v.FixedEnvelopeSize {
			t.Fatalf("%s: envelope is %d bytes, want exactly %d — a size delta leaks the duress bit",
				e.Name, len(e.Body), v.FixedEnvelopeSize)
		}
	}
	// And explicitly across the duress boundary, which is the attacker's view.
	var normal, duress []int
	for _, e := range v.Envelopes {
		if e.Duress {
			duress = append(duress, len(e.Body))
		} else {
			normal = append(normal, len(e.Body))
		}
	}
	if len(normal) == 0 || len(duress) == 0 {
		t.Fatal("vectors must contain both duress and non-duress envelopes")
	}
	for _, n := range normal {
		for _, d := range duress {
			if n != d {
				t.Fatalf("duress envelope (%d B) distinguishable from normal (%d B)", d, n)
			}
		}
	}
}

// TestClientSMSDecodes: the T0 encoder against this package's parser.
func TestClientSMSDecodes(t *testing.T) {
	v := loadVectors(t)
	for _, s := range v.SMS {
		t.Run(s.Name, func(t *testing.T) {
			if s.Length > 160 {
				t.Fatalf("payload is %d chars, over the 160 GSM-7 limit (I-2)", s.Length)
			}
			for i, r := range s.Text {
				if r < 32 || r > 126 {
					t.Fatalf("non-GSM7 rune %q at %d — UCS-2 would cut the limit to 70 (P-033)", r, i)
				}
			}
			got, _, ok := DecodeSMS(s.Text)
			if !ok {
				t.Fatal("server could not decode a payload the client produced")
			}
			if got.Inc8 != s.Inc8 {
				t.Fatalf("inc8: got %q want %q — SMS reconciliation (F-09) would fork a duplicate incident", got.Inc8, s.Inc8)
			}
			if got.Code != s.ExpectedCode {
				t.Fatalf("trigger code: got %q want %q", got.Code, s.ExpectedCode)
			}
			// Six decimal places is the wire precision, so allow half a ulp there.
			if diff := got.Lat - s.Lat; diff > 1e-6 || diff < -1e-6 {
				t.Fatalf("lat: got %v want %v", got.Lat, s.Lat)
			}
			if diff := got.Lon - s.Lon; diff > 1e-6 || diff < -1e-6 {
				t.Fatalf("lon: got %v want %v", got.Lon, s.Lon)
			}
		})
	}
}

// TestInc8AgreesAcrossLanguages — F-09. If these disagree, an SMS-originated
// incident never finds its HTTP twin and the family sees the same emergency twice.
func TestInc8AgreesAcrossLanguages(t *testing.T) {
	v := loadVectors(t)
	for _, c := range v.Inc8 {
		if got := Inc8(c.IncidentID); got != c.Inc8 {
			t.Fatalf("Inc8(%s): server %q, client %q", c.IncidentID, got, c.Inc8)
		}
	}
}

// TestSMSTagAgreesAcrossLanguages — the HMAC the aggregator webhook checks.
func TestSMSTagAgreesAcrossLanguages(t *testing.T) {
	v := loadVectors(t)
	key, err := base64.StdEncoding.DecodeString(v.SMSTag.GroupSecretB64)
	if err != nil {
		t.Fatalf("decode group secret: %v", err)
	}
	if got := SMSTag(key, v.SMSTag.Payload); got != v.SMSTag.Tag {
		t.Fatalf("SMSTag: server %q, client %q", got, v.SMSTag.Tag)
	}
}

// TestTamperedEnvelopeFailsVerification — the signature must actually be load
// bearing. (Ingest then accepts it anyway and flags UNVERIFIED per ADR-018;
// this asserts the FLAG is correct, not that the request is rejected.)
func TestTamperedEnvelopeFailsVerification(t *testing.T) {
	v := loadVectors(t)
	e := v.Envelopes[0]
	pub, _ := base64.StdEncoding.DecodeString(e.PublicKey)
	tampered := strings.Replace(e.Body, `"batteryPct":43`, `"batteryPct":44`, 1)
	if tampered == e.Body {
		t.Skip("vector shape changed; nothing tampered")
	}
	if VerifyB64([]byte(tampered), e.Signature, ed25519.PublicKey(pub)) {
		t.Fatal("a tampered body verified — the signature is not load bearing")
	}
}
