// Code generated by tools/smgen.mjs from spec/state-machine.yaml. DO NOT EDIT.
// Regenerate with:  npm run gen

package incident

const SpecVersion = 3

type State string
type Event string

const (
	StateIdle State = "IDLE"
	StateWatch State = "WATCH"
	StateSuspect State = "SUSPECT"
	StateProbe State = "PROBE"
	StatePending State = "PENDING"
	StateFalseAlarm State = "FALSE_ALARM"
	StateActiveL1 State = "ACTIVE_L1"
	StateActiveL1Silent State = "ACTIVE_L1_SILENT"
	StateActiveL2 State = "ACTIVE_L2"
	StateActiveL3 State = "ACTIVE_L3"
	StateOwned State = "OWNED"
	StateResolving State = "RESOLVING"
	StateResolved State = "RESOLVED"
	StateDormant State = "DORMANT"
)

const (
	EventContextElevated Event = "CONTEXT_ELEVATED"
	EventContextEnded Event = "CONTEXT_ENDED"
	EventSensorAnomaly Event = "SENSOR_ANOMALY"
	EventConfidence Event = "CONFIDENCE"
	EventUserFine Event = "USER_FINE"
	EventManualTrigger Event = "MANUAL_TRIGGER"
	EventPinCorrect Event = "PIN_CORRECT"
	EventPinDuress Event = "PIN_DURESS"
	EventCancelWindowExpired Event = "CANCEL_WINDOW_EXPIRED"
	EventProbeTimeout Event = "PROBE_TIMEOUT"
	EventNoAck Event = "NO_ACK"
	EventClaim Event = "CLAIM"
	EventRelease Event = "RELEASE"
	EventProgressWatchdog Event = "PROGRESS_WATCHDOG"
	EventOnScene Event = "ON_SCENE"
	EventTwoPartyConfirm Event = "TWO_PARTY_CONFIRM"
	EventSelfClearPin Event = "SELF_CLEAR_PIN"
	EventAutoQuiesce Event = "AUTO_QUIESCE"
	EventReescalate Event = "REESCALATE"
	EventMotionResumed Event = "MOTION_RESUMED"
)

var AllStates = []State{
	StateIdle,
	StateWatch,
	StateSuspect,
	StateProbe,
	StatePending,
	StateFalseAlarm,
	StateActiveL1,
	StateActiveL1Silent,
	StateActiveL2,
	StateActiveL3,
	StateOwned,
	StateResolving,
	StateResolved,
	StateDormant,
}

var terminalStates = map[State]bool{
	StateFalseAlarm: true,
	StateResolved: true,
	StateDormant: true,
}

// activeStates: the incident is live — escalation timers armed, deploys blocked.
var activeStates = map[State]bool{
	StatePending: true,
	StateActiveL1: true,
	StateActiveL1Silent: true,
	StateActiveL2: true,
	StateActiveL3: true,
	StateOwned: true,
	StateResolving: true,
}

type Transition struct {
	From   State
	To     State
	On     Event
	Guard  string
	AfterS int
}

var Transitions = []Transition{
	{From: StateIdle, To: StateWatch, On: EventContextElevated, Guard: "", AfterS: 0},
	{From: StateWatch, To: StateIdle, On: EventContextEnded, Guard: "", AfterS: 0},
	{From: StateIdle, To: StateSuspect, On: EventSensorAnomaly, Guard: "", AfterS: 0},
	{From: StateWatch, To: StateSuspect, On: EventSensorAnomaly, Guard: "lowerThreshold", AfterS: 0},
	{From: StateSuspect, To: StateIdle, On: EventMotionResumed, Guard: "", AfterS: 0},
	{From: StateSuspect, To: StateProbe, On: EventConfidence, Guard: "confidenceMedium", AfterS: 0},
	{From: StateSuspect, To: StatePending, On: EventConfidence, Guard: "confidenceHigh", AfterS: 0},
	{From: StateProbe, To: StateIdle, On: EventUserFine, Guard: "", AfterS: 0},
	{From: StateProbe, To: StatePending, On: EventProbeTimeout, Guard: "", AfterS: 45},
	{From: StateIdle, To: StatePending, On: EventManualTrigger, Guard: "", AfterS: 0},
	{From: StateWatch, To: StatePending, On: EventManualTrigger, Guard: "", AfterS: 0},
	{From: StatePending, To: StateFalseAlarm, On: EventPinCorrect, Guard: "", AfterS: 0},
	{From: StatePending, To: StateActiveL1Silent, On: EventPinDuress, Guard: "", AfterS: 0},
	{From: StatePending, To: StateActiveL1, On: EventCancelWindowExpired, Guard: "", AfterS: 0},
	{From: StateActiveL1, To: StateActiveL2, On: EventNoAck, Guard: "", AfterS: 90},
	{From: StateActiveL1Silent, To: StateActiveL2, On: EventNoAck, Guard: "", AfterS: 90},
	{From: StateActiveL2, To: StateActiveL3, On: EventNoAck, Guard: "", AfterS: 180},
	{From: StateActiveL1, To: StateOwned, On: EventClaim, Guard: "", AfterS: 0},
	{From: StateActiveL1Silent, To: StateOwned, On: EventClaim, Guard: "", AfterS: 0},
	{From: StateActiveL2, To: StateOwned, On: EventClaim, Guard: "", AfterS: 0},
	{From: StateActiveL3, To: StateOwned, On: EventClaim, Guard: "", AfterS: 0},
	{From: StateOwned, To: StateActiveL2, On: EventRelease, Guard: "", AfterS: 0},
	{From: StateOwned, To: StateActiveL2, On: EventProgressWatchdog, Guard: "", AfterS: 300},
	{From: StateOwned, To: StateResolving, On: EventOnScene, Guard: "", AfterS: 0},
	{From: StateResolving, To: StateResolved, On: EventTwoPartyConfirm, Guard: "", AfterS: 0},
	{From: StateActiveL1, To: StateResolved, On: EventSelfClearPin, Guard: "", AfterS: 0},
	{From: StateActiveL2, To: StateResolved, On: EventSelfClearPin, Guard: "", AfterS: 0},
	{From: StateActiveL3, To: StateResolved, On: EventSelfClearPin, Guard: "", AfterS: 0},
	{From: StateActiveL1, To: StateDormant, On: EventAutoQuiesce, Guard: "", AfterS: 21600},
	{From: StateActiveL1Silent, To: StateDormant, On: EventAutoQuiesce, Guard: "", AfterS: 21600},
	{From: StateActiveL2, To: StateDormant, On: EventAutoQuiesce, Guard: "", AfterS: 21600},
	{From: StateActiveL3, To: StateDormant, On: EventAutoQuiesce, Guard: "", AfterS: 21600},
	{From: StateOwned, To: StateDormant, On: EventAutoQuiesce, Guard: "", AfterS: 21600},
	{From: StateActiveL1, To: StateActiveL2, On: EventReescalate, Guard: "", AfterS: 0},
	{From: StateActiveL2, To: StateActiveL3, On: EventReescalate, Guard: "", AfterS: 0},
}

// Guards the caller supplies. A guard that is absent evaluates false, EXCEPT
// that a transition with no guard always applies.
type Guards map[string]bool

// NextState is pure: no side effects, no I/O, no clock. It returns ok=false when
// the event does not apply — unknown events are ignored, never an error.
func NextState(from State, event Event, guards Guards) (State, bool) {
	for _, t := range Transitions {
		if t.From != from || t.On != event {
			continue
		}
		if t.Guard != "" && !guards[t.Guard] {
			continue
		}
		return t.To, true
	}
	return from, false
}

// TimeoutsFor returns the scheduled transitions out of a state.
func TimeoutsFor(s State) []Transition {
	var out []Transition
	for _, t := range Transitions {
		if t.From == s && t.AfterS > 0 {
			out = append(out, t)
		}
	}
	return out
}

func IsTerminal(s State) bool { return terminalStates[s] }
func IsActive(s State) bool   { return activeStates[s] }

type FoldEvent struct {
	Event  Event
	Guards Guards
}

// Fold recomputes the projection from the event log. incident.state is always
// a materialised projection; if it is ever wrong, recompute it (PRD §7.5).
func Fold(events []FoldEvent, from State) State {
	s := from
	for _, e := range events {
		if n, ok := NextState(s, e.Event, e.Guards); ok {
			s = n
		}
	}
	return s
}
