// Code generated by tools/smgen.mjs from spec/state-machine.yaml. DO NOT EDIT.
// Regenerate with:  npm run gen

package incident

import "testing"

// TestConformanceFixtures runs the SAME fixture set as the TypeScript client.
// If this test and the client test ever disagree, the two implementations have
// diverged and the build must fail.
func TestConformanceFixtures(t *testing.T) {
	cases := []struct {
		name   string
		from   State
		steps  []FoldEvent
		expect State
	}{
		{
			name:   "manual panic runs the full ladder to L3",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventNoAck, Guards: Guards{"lowerThreshold": true}}, {Event: EventNoAck, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL3,
		},
		{
			name:   "correct PIN cancels",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventPinCorrect, Guards: Guards{"lowerThreshold": true}}},
			expect: StateFalseAlarm,
		},
		{
			name:   "duress PIN escalates silently",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventPinDuress, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL1Silent,
		},
		{
			name:   "duress still climbs the ladder",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventPinDuress, Guards: Guards{"lowerThreshold": true}}, {Event: EventNoAck, Guards: Guards{"lowerThreshold": true}}, {Event: EventNoAck, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL3,
		},
		{
			name:   "claim halts the ladder",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventClaim, Guards: Guards{"lowerThreshold": true}}},
			expect: StateOwned,
		},
		{
			name:   "release re-broadcasts at L2",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventClaim, Guards: Guards{"lowerThreshold": true}}, {Event: EventRelease, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL2,
		},
		{
			name:   "progress watchdog re-broadcasts",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventClaim, Guards: Guards{"lowerThreshold": true}}, {Event: EventProgressWatchdog, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL2,
		},
		{
			name:   "two-party resolution",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventClaim, Guards: Guards{"lowerThreshold": true}}, {Event: EventOnScene, Guards: Guards{"lowerThreshold": true}}, {Event: EventTwoPartyConfirm, Guards: Guards{"lowerThreshold": true}}},
			expect: StateResolved,
		},
		{
			name:   "PROBE absorbs a medium-confidence anomaly",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventSensorAnomaly, Guards: Guards{"lowerThreshold": true}}, {Event: EventConfidence, Guards: Guards{"confidenceMedium": true, "lowerThreshold": true}}, {Event: EventUserFine, Guards: Guards{"lowerThreshold": true}}},
			expect: StateIdle,
		},
		{
			name:   "PROBE timeout escalates",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventSensorAnomaly, Guards: Guards{"lowerThreshold": true}}, {Event: EventConfidence, Guards: Guards{"confidenceMedium": true, "lowerThreshold": true}}, {Event: EventProbeTimeout, Guards: Guards{"lowerThreshold": true}}},
			expect: StatePending,
		},
		{
			name:   "high confidence skips PROBE",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventSensorAnomaly, Guards: Guards{"lowerThreshold": true}}, {Event: EventConfidence, Guards: Guards{"confidenceHigh": true, "lowerThreshold": true}}},
			expect: StatePending,
		},
		{
			name:   "watch lowers the anomaly threshold",
			from:   StateWatch,
			steps:  []FoldEvent{{Event: EventSensorAnomaly, Guards: Guards{"lowerThreshold": true}}},
			expect: StateSuspect,
		},
		{
			name:   "motion resumed auto-resolves a suspect",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventSensorAnomaly, Guards: Guards{"lowerThreshold": true}}, {Event: EventMotionResumed, Guards: Guards{"lowerThreshold": true}}},
			expect: StateIdle,
		},
		{
			name:   "auto-quiesce ends a forgotten incident",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventAutoQuiesce, Guards: Guards{"lowerThreshold": true}}},
			expect: StateDormant,
		},
		{
			name:   "reescalate jumps the ladder",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventManualTrigger, Guards: Guards{"lowerThreshold": true}}, {Event: EventCancelWindowExpired, Guards: Guards{"lowerThreshold": true}}, {Event: EventReescalate, Guards: Guards{"lowerThreshold": true}}},
			expect: StateActiveL2,
		},
		{
			name:   "unknown events are ignored, never crash",
			from:   StateIdle,
			steps:  []FoldEvent{{Event: EventNoAck, Guards: Guards{"lowerThreshold": true}}, {Event: EventClaim, Guards: Guards{"lowerThreshold": true}}, {Event: EventRelease, Guards: Guards{"lowerThreshold": true}}},
			expect: StateIdle,
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := Fold(c.steps, c.from); got != c.expect {
				t.Fatalf("got %s, want %s", got, c.expect)
			}
		})
	}
}

// TestNoAmbiguousTransitions guards the property the generator enforces.
func TestNoAmbiguousTransitions(t *testing.T) {
	seen := map[string]State{}
	for _, tr := range Transitions {
		k := string(tr.From) + "|" + string(tr.On) + "|" + tr.Guard
		if prev, ok := seen[k]; ok {
			t.Fatalf("ambiguous transition %s: %s and %s", k, prev, tr.To)
		}
		seen[k] = tr.To
	}
}

// TestUnknownEventsAreIgnored — a panic in the escalation path is unacceptable.
func TestUnknownEventsAreIgnored(t *testing.T) {
	for _, s := range AllStates {
		if got, ok := NextState(s, Event("NOT_A_REAL_EVENT"), nil); ok || got != s {
			t.Fatalf("state %s mutated on an unknown event", s)
		}
	}
}
