#!/usr/bin/env node
/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * smgen — Kavach state-machine code generator
 *
 * Reads   spec/state-machine.yaml   (the single source of truth)
 * Emits   mobile/src/t0/stateMachine.generated.ts
 *         backend/internal/incident/machine_gen.go
 *         backend/internal/incident/machine_gen_test.go   (conformance fixtures)
 *         mobile/src/t0/__tests__/stateMachine.fixtures.json
 *
 * PRD §7.5: "The machine is implemented twice ... Both are generated from ONE
 * shared table of transitions checked into the repo as YAML, with a code
 * generator. Divergence between the two implementations is a class of bug you
 * cannot afford."
 *
 * Usage:  node tools/smgen.mjs           regenerate
 *         node tools/smgen.mjs --check   fail if generated files are stale (CI)
 * ═══════════════════════════════════════════════════════════════════════════════
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'spec', 'state-machine.yaml');
const CHECK = process.argv.includes('--check');

const spec = yaml.load(fs.readFileSync(SPEC, 'utf8'));

// ── Validation ────────────────────────────────────────────────────────────────
const states = new Set(spec.states);
const events = new Set(spec.events);
const errors = [];

for (const t of spec.transitions) {
  if (!states.has(t.from)) errors.push(`unknown 'from' state: ${t.from}`);
  if (!states.has(t.to)) errors.push(`unknown 'to' state: ${t.to}`);
  if (!events.has(t.on)) errors.push(`unknown event: ${t.on}`);
}
for (const s of spec.terminal ?? []) if (!states.has(s)) errors.push(`unknown terminal state: ${s}`);
for (const s of spec.active ?? []) if (!states.has(s)) errors.push(`unknown active state: ${s}`);

// A (from,on,guard) triple must be unique — otherwise the transition is ambiguous
// and the two implementations could pick different targets.
const seen = new Map();
for (const t of spec.transitions) {
  const key = `${t.from}|${t.on}|${t.guard ?? ''}`;
  if (seen.has(key)) errors.push(`ambiguous transition: ${key} → ${seen.get(key)} and → ${t.to}`);
  seen.set(key, t.to);
}
if (errors.length) {
  console.error('✖ state-machine.yaml is invalid:\n' + errors.map((e) => '  - ' + e).join('\n'));
  process.exit(1);
}

// ── Fixture expansion ─────────────────────────────────────────────────────────
// Fixtures use pseudo-events CONFIDENCE_MEDIUM / CONFIDENCE_HIGH which expand to
// the CONFIDENCE event plus the corresponding guard.
function expandFixtureEvent(e) {
  if (e === 'CONFIDENCE_MEDIUM') return { event: 'CONFIDENCE', guards: ['confidenceMedium', 'lowerThreshold'] };
  if (e === 'CONFIDENCE_HIGH') return { event: 'CONFIDENCE', guards: ['confidenceHigh', 'lowerThreshold'] };
  return { event: e, guards: ['lowerThreshold'] };
}
const fixtures = (spec.fixtures ?? []).map((f) => ({
  name: f.name,
  from: f.from,
  expect: f.expect,
  steps: f.events.map(expandFixtureEvent),
}));

const banner = (tool) =>
  `// Code generated by ${tool} from spec/state-machine.yaml. DO NOT EDIT.\n` +
  `// Regenerate with:  npm run gen\n`;

// ══════════════════════════════════════════════════════════════════════════════
// TypeScript emitter
// ══════════════════════════════════════════════════════════════════════════════
function emitTS() {
  const L = [];
  L.push(banner('tools/smgen.mjs'));
  L.push(`/* eslint-disable */`);
  L.push(``);
  L.push(`export const SPEC_VERSION = ${spec.version};`);
  L.push(``);
  L.push(`export const INCIDENT_STATES = [`);
  for (const s of spec.states) L.push(`  '${s}',`);
  L.push(`] as const;`);
  L.push(`export type IncidentState = (typeof INCIDENT_STATES)[number];`);
  L.push(``);
  L.push(`export const INCIDENT_EVENTS = [`);
  for (const e of spec.events) L.push(`  '${e}',`);
  L.push(`] as const;`);
  L.push(`export type IncidentEvent = (typeof INCIDENT_EVENTS)[number];`);
  L.push(``);
  L.push(`export const TERMINAL_STATES: ReadonlySet<IncidentState> = new Set([`);
  for (const s of spec.terminal ?? []) L.push(`  '${s}',`);
  L.push(`]);`);
  L.push(``);
  L.push(`/** States in which the incident is live: arms escalation timers, blocks deploys. */`);
  L.push(`export const ACTIVE_STATES: ReadonlySet<IncidentState> = new Set([`);
  for (const s of spec.active ?? []) L.push(`  '${s}',`);
  L.push(`]);`);
  L.push(``);
  L.push(`export interface Transition {`);
  L.push(`  readonly from: IncidentState;`);
  L.push(`  readonly to: IncidentState;`);
  L.push(`  readonly on: IncidentEvent;`);
  L.push(`  readonly guard?: string;`);
  L.push(`  readonly afterS?: number;`);
  L.push(`}`);
  L.push(``);
  L.push(`export const TRANSITIONS: readonly Transition[] = [`);
  for (const t of spec.transitions) {
    const parts = [`from: '${t.from}'`, `to: '${t.to}'`, `on: '${t.on}'`];
    if (t.guard) parts.push(`guard: '${t.guard}'`);
    if (t.afterS != null) parts.push(`afterS: ${t.afterS}`);
    L.push(`  { ${parts.join(', ')} },`);
  }
  L.push(`];`);
  L.push(``);
  L.push(`/** Guards the runtime must supply. A missing guard evaluates to TRUE (fail open, ADR-018). */`);
  L.push(`export type GuardSet = Partial<Record<string, boolean>>;`);
  L.push(``);
  L.push(`/**`);
  L.push(` * Pure transition function. No side effects, no I/O, no clock.`);
  L.push(` * Returns null when the event does not apply in the current state —`);
  L.push(` * unknown events are ALWAYS ignored, never thrown (a crash in T0 is fatal).`);
  L.push(` */`);
  L.push(`export function nextState(`);
  L.push(`  from: IncidentState,`);
  L.push(`  event: IncidentEvent,`);
  L.push(`  guards: GuardSet = {},`);
  L.push(`): IncidentState | null {`);
  L.push(`  for (const t of TRANSITIONS) {`);
  L.push(`    if (t.from !== from || t.on !== event) continue;`);
  L.push(`    if (t.guard !== undefined && guards[t.guard] !== true) continue;`);
  L.push(`    return t.to;`);
  L.push(`  }`);
  L.push(`  return null;`);
  L.push(`}`);
  L.push(``);
  L.push(`/** The scheduled timeout (seconds) for a state, if the spec defines one. */`);
  L.push(`export function timeoutsFor(state: IncidentState): Transition[] {`);
  L.push(`  return TRANSITIONS.filter((t) => t.from === state && t.afterS !== undefined);`);
  L.push(`}`);
  L.push(``);
  L.push(`export function isTerminal(s: IncidentState): boolean { return TERMINAL_STATES.has(s); }`);
  L.push(`export function isActive(s: IncidentState): boolean { return ACTIVE_STATES.has(s); }`);
  L.push(``);
  L.push(`/** Fold an event log into a state. The projection is always recomputable (PRD §7.5). */`);
  L.push(`export function fold(`);
  L.push(`  events: ReadonlyArray<{ event: IncidentEvent; guards?: GuardSet }>,`);
  L.push(`  from: IncidentState = 'IDLE',`);
  L.push(`): IncidentState {`);
  L.push(`  let s = from;`);
  L.push(`  for (const e of events) {`);
  L.push(`    const n = nextState(s, e.event, e.guards ?? {});`);
  L.push(`    if (n !== null) s = n;`);
  L.push(`  }`);
  L.push(`  return s;`);
  L.push(`}`);
  L.push(``);
  return L.join('\n');
}

// ══════════════════════════════════════════════════════════════════════════════
// Go emitter
// ══════════════════════════════════════════════════════════════════════════════
function emitGo() {
  const L = [];
  L.push(banner('tools/smgen.mjs'));
  L.push(`package incident`);
  L.push(``);
  L.push(`const SpecVersion = ${spec.version}`);
  L.push(``);
  L.push(`type State string`);
  L.push(`type Event string`);
  L.push(``);
  L.push(`const (`);
  for (const s of spec.states) L.push(`\tState${pascal(s)} State = "${s}"`);
  L.push(`)`);
  L.push(``);
  L.push(`const (`);
  for (const e of spec.events) L.push(`\tEvent${pascal(e)} Event = "${e}"`);
  L.push(`)`);
  L.push(``);
  L.push(`var AllStates = []State{`);
  for (const s of spec.states) L.push(`\tState${pascal(s)},`);
  L.push(`}`);
  L.push(``);
  L.push(`var terminalStates = map[State]bool{`);
  for (const s of spec.terminal ?? []) L.push(`\tState${pascal(s)}: true,`);
  L.push(`}`);
  L.push(``);
  L.push(`// activeStates: the incident is live — escalation timers armed, deploys blocked.`);
  L.push(`var activeStates = map[State]bool{`);
  for (const s of spec.active ?? []) L.push(`\tState${pascal(s)}: true,`);
  L.push(`}`);
  L.push(``);
  L.push(`type Transition struct {`);
  L.push(`\tFrom   State`);
  L.push(`\tTo     State`);
  L.push(`\tOn     Event`);
  L.push(`\tGuard  string`);
  L.push(`\tAfterS int`);
  L.push(`}`);
  L.push(``);
  L.push(`var Transitions = []Transition{`);
  for (const t of spec.transitions) {
    L.push(
      `\t{From: State${pascal(t.from)}, To: State${pascal(t.to)}, On: Event${pascal(t.on)}, Guard: "${t.guard ?? ''}", AfterS: ${t.afterS ?? 0}},`,
    );
  }
  L.push(`}`);
  L.push(``);
  L.push(`// Guards the caller supplies. A guard that is absent evaluates false, EXCEPT`);
  L.push(`// that a transition with no guard always applies.`);
  L.push(`type Guards map[string]bool`);
  L.push(``);
  L.push(`// NextState is pure: no side effects, no I/O, no clock. It returns ok=false when`);
  L.push(`// the event does not apply — unknown events are ignored, never an error.`);
  L.push(`func NextState(from State, event Event, guards Guards) (State, bool) {`);
  L.push(`\tfor _, t := range Transitions {`);
  L.push(`\t\tif t.From != from || t.On != event {`);
  L.push(`\t\t\tcontinue`);
  L.push(`\t\t}`);
  L.push(`\t\tif t.Guard != "" && !guards[t.Guard] {`);
  L.push(`\t\t\tcontinue`);
  L.push(`\t\t}`);
  L.push(`\t\treturn t.To, true`);
  L.push(`\t}`);
  L.push(`\treturn from, false`);
  L.push(`}`);
  L.push(``);
  L.push(`// TimeoutsFor returns the scheduled transitions out of a state.`);
  L.push(`func TimeoutsFor(s State) []Transition {`);
  L.push(`\tvar out []Transition`);
  L.push(`\tfor _, t := range Transitions {`);
  L.push(`\t\tif t.From == s && t.AfterS > 0 {`);
  L.push(`\t\t\tout = append(out, t)`);
  L.push(`\t\t}`);
  L.push(`\t}`);
  L.push(`\treturn out`);
  L.push(`}`);
  L.push(``);
  L.push(`func IsTerminal(s State) bool { return terminalStates[s] }`);
  L.push(`func IsActive(s State) bool   { return activeStates[s] }`);
  L.push(``);
  L.push(`type FoldEvent struct {`);
  L.push(`\tEvent  Event`);
  L.push(`\tGuards Guards`);
  L.push(`}`);
  L.push(``);
  L.push(`// Fold recomputes the projection from the event log. incident.state is always`);
  L.push(`// a materialised projection; if it is ever wrong, recompute it (PRD §7.5).`);
  L.push(`func Fold(events []FoldEvent, from State) State {`);
  L.push(`\ts := from`);
  L.push(`\tfor _, e := range events {`);
  L.push(`\t\tif n, ok := NextState(s, e.Event, e.Guards); ok {`);
  L.push(`\t\t\ts = n`);
  L.push(`\t\t}`);
  L.push(`\t}`);
  L.push(`\treturn s`);
  L.push(`}`);
  L.push(``);
  return L.join('\n');
}

function emitGoTest() {
  const L = [];
  L.push(banner('tools/smgen.mjs'));
  L.push(`package incident`);
  L.push(``);
  L.push(`import "testing"`);
  L.push(``);
  L.push(`// TestConformanceFixtures runs the SAME fixture set as the TypeScript client.`);
  L.push(`// If this test and the client test ever disagree, the two implementations have`);
  L.push(`// diverged and the build must fail.`);
  L.push(`func TestConformanceFixtures(t *testing.T) {`);
  L.push(`\tcases := []struct {`);
  L.push(`\t\tname   string`);
  L.push(`\t\tfrom   State`);
  L.push(`\t\tsteps  []FoldEvent`);
  L.push(`\t\texpect State`);
  L.push(`\t}{`);
  for (const f of fixtures) {
    const steps = f.steps
      .map((s) => `{Event: Event${pascal(s.event)}, Guards: Guards{${s.guards.map((g) => `"${g}": true`).join(', ')}}}`)
      .join(', ');
    L.push(`\t\t{`);
    L.push(`\t\t\tname:   ${JSON.stringify(f.name)},`);
    L.push(`\t\t\tfrom:   State${pascal(f.from)},`);
    L.push(`\t\t\tsteps:  []FoldEvent{${steps}},`);
    L.push(`\t\t\texpect: State${pascal(f.expect)},`);
    L.push(`\t\t},`);
  }
  L.push(`\t}`);
  L.push(`\tfor _, c := range cases {`);
  L.push(`\t\tt.Run(c.name, func(t *testing.T) {`);
  L.push(`\t\t\tif got := Fold(c.steps, c.from); got != c.expect {`);
  L.push(`\t\t\t\tt.Fatalf("got %s, want %s", got, c.expect)`);
  L.push(`\t\t\t}`);
  L.push(`\t\t})`);
  L.push(`\t}`);
  L.push(`}`);
  L.push(``);
  L.push(`// TestNoAmbiguousTransitions guards the property the generator enforces.`);
  L.push(`func TestNoAmbiguousTransitions(t *testing.T) {`);
  L.push(`\tseen := map[string]State{}`);
  L.push(`\tfor _, tr := range Transitions {`);
  L.push(`\t\tk := string(tr.From) + "|" + string(tr.On) + "|" + tr.Guard`);
  L.push(`\t\tif prev, ok := seen[k]; ok {`);
  L.push(`\t\t\tt.Fatalf("ambiguous transition %s: %s and %s", k, prev, tr.To)`);
  L.push(`\t\t}`);
  L.push(`\t\tseen[k] = tr.To`);
  L.push(`\t}`);
  L.push(`}`);
  L.push(``);
  L.push(`// TestUnknownEventsAreIgnored — a panic in the escalation path is unacceptable.`);
  L.push(`func TestUnknownEventsAreIgnored(t *testing.T) {`);
  L.push(`\tfor _, s := range AllStates {`);
  L.push(`\t\tif got, ok := NextState(s, Event("NOT_A_REAL_EVENT"), nil); ok || got != s {`);
  L.push(`\t\t\tt.Fatalf("state %s mutated on an unknown event", s)`);
  L.push(`\t\t}`);
  L.push(`\t}`);
  L.push(`}`);
  L.push(``);
  return L.join('\n');
}

function pascal(s) {
  return s
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

// ── Write ─────────────────────────────────────────────────────────────────────
const outputs = [
  ['mobile/src/t0/stateMachine.generated.ts', emitTS()],
  ['backend/internal/incident/machine_gen.go', emitGo()],
  ['backend/internal/incident/machine_gen_test.go', emitGoTest()],
  ['mobile/src/t0/__generated__/fixtures.json', JSON.stringify(fixtures, null, 2) + '\n'],
];

let stale = 0;
for (const [rel, content] of outputs) {
  const abs = path.join(ROOT, rel);
  const prev = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (prev === content) {
    console.log(`  = ${rel}`);
    continue;
  }
  stale++;
  if (CHECK) {
    console.error(`  ✖ STALE ${rel}`);
    continue;
  }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  console.log(`  ✔ ${rel}`);
}

if (CHECK && stale > 0) {
  console.error(`\n✖ ${stale} generated file(s) are stale. Run: npm run gen`);
  process.exit(1);
}
console.log(
  `\n✔ ${spec.states.length} states · ${spec.events.length} events · ${spec.transitions.length} transitions · ${fixtures.length} fixtures`,
);
